version: '3'
services:
 mysqldb:
  container_name: mysqldb
  image: "pmathivanan/mysqldb:2"
  ports:
  - "8092:3306"
 myspringbootapp:
  container_name: myspringbootapp
  image: "pmathivanan/myspringbootapp:4"
  ports:
  - "8091:8090"
  depends_on:
  - mysqldb
 


